version: '3.1'

services:
  db10:
    container_name: odoo10-db
    restart: unless-stopped
    image: postgres:12
    ports:
      - "10001:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    networks:
        public:
            ipv4_address: 10.0.1.22
    volumes:
      - ./data-odoo10:/var/lib/postgresql/data

  db14:
    container_name: odoo14-db
    restart: unless-stopped
    image: postgres:12
    ports:
      - "14001:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    networks:
        public:
            ipv4_address: 10.0.1.20
    volumes:
      - ./data-odoo14:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db10
      - db14
    networks:
        public:
            ipv4_address: 10.0.1.60
    restart: unless-stopped

networks:
  public:
    external:
      name: public

volumes:
    pgadmin:
